/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PhotoItemImage = {
  asset?: SanityImageAssetReference;
  media?: unknown // Unable to locate the referenced type "media" in schema
  ;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type PhotoColumn = {
  _type: "photoColumn";
  photos?: Array<{
    isVideo?: boolean;
    image?: PhotoItemImage;
    previewVideoUrl?: string;
    fullVideoUrl?: string;
    alt?: string;
    displayMode?: "stacked" | "fullscreen";
    _type: "photoItem";
    _key: string;
  }>;
};

export type ExternalLink = {
  _type: "externalLink";
  label?: string;
  linkType?: "external" | "email";
  url?: string;
  email?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "foto" | "movement-direction" | "performance";
  description?: BlockContent;
  relevantLinks?: Array<{
    _key: string;
  } & ExternalLink>;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  leftColumn?: PhotoColumn;
  rightColumn?: PhotoColumn;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  footerLeftText?: string;
  footerRightText?: string;
  footerCenterText?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    metadataBase?: string;
    _type: "image";
  };
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainText?: BlockContent;
  selectedClients?: string;
  selectedClientsDescription?: string;
  specialties?: Array<string>;
  contact?: Array<{
    _key: string;
  } & ExternalLink>;
  backgroundColor?: Color;
  seoTitle?: string;
  seoDescription?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  fotoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  movementDirectionImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  performanceImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  previewVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | PhotoItemImage | PhotoColumn | ExternalLink | BlockContent | Project | SanityImageCrop | SanityImageHotspot | Slug | Settings | About | Color | SanityFileAssetReference | Homepage | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | AssistInstructionContextReference | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && _id == "siteSettings"][0]{    title,    description,    footerLeftText,    footerRightText,    footerCenterText,    ogImage  }
export type SettingsQueryResult = {
  title: string | null;
  description: string | null;
  footerLeftText: string | null;
  footerRightText: string | null;
  footerCenterText: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    metadataBase?: string;
    _type: "image";
  } | null;
} | null;
// Variable: homepageQuery
// Query: *[_type == "homepage" && _id == "homepage"][0]{    _id,    title,    fotoImage,    movementDirectionImage,    performanceImage,    "previewVideoUrl": previewVideo.asset->url,    seoTitle,    seoDescription  }
export type HomepageQueryResult = {
  _id: string;
  title: string | null;
  fotoImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  movementDirectionImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  performanceImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  previewVideoUrl: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;
// Variable: aboutQuery
// Query: *[_type == "about" && _id == "about"][0]{    _id,    mainText,    selectedClients,    selectedClientsDescription,    specialties,    contact[]{      _key,      label,      linkType,      url,      email    },    backgroundColor,    seoTitle,    seoDescription  }
export type AboutQueryResult = {
  _id: string;
  mainText: BlockContent | null;
  selectedClients: string | null;
  selectedClientsDescription: string | null;
  specialties: Array<string> | null;
  contact: Array<{
    _key: string;
    label: string | null;
    linkType: "email" | "external" | null;
    url: string | null;
    email: string | null;
  }> | null;
  backgroundColor: Color | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;
// Variable: allProjectsForNavQuery
// Query: {    "foto": *[_type == "project" && category == "foto"] | order(title asc) {      _id,      title,      "slug": slug.current    },    "movementDirection": *[_type == "project" && category == "movement-direction"] | order(title asc) {      _id,      title,      "slug": slug.current    },    "performance": *[_type == "project" && category == "performance"] | order(title asc) {      _id,      title,      "slug": slug.current    }  }
export type AllProjectsForNavQueryResult = {
  foto: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }>;
  movementDirection: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }>;
  performance: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }>;
};
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    category,    description,    relevantLinks[]{      _key,      label,      linkType,      url,      email    },    featuredImage,    leftColumn{      photos[]{        _key,        "isVideo": coalesce(isVideo, false),        image,        previewVideoUrl,        fullVideoUrl,        alt,        displayMode      }    },    rightColumn{      photos[]{        _key,        "isVideo": coalesce(isVideo, false),        image,        previewVideoUrl,        fullVideoUrl,        alt,        displayMode      }    },    seoTitle,    seoDescription  }
export type ProjectBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  category: "foto" | "movement-direction" | "performance" | null;
  description: BlockContent | null;
  relevantLinks: Array<{
    _key: string;
    label: string | null;
    linkType: "email" | "external" | null;
    url: string | null;
    email: string | null;
  }> | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  leftColumn: {
    photos: Array<{
      _key: string;
      isVideo: boolean | false;
      image: PhotoItemImage | null;
      previewVideoUrl: string | null;
      fullVideoUrl: string | null;
      alt: string | null;
      displayMode: "fullscreen" | "stacked" | null;
    }> | null;
  } | null;
  rightColumn: {
    photos: Array<{
      _key: string;
      isVideo: boolean | false;
      image: PhotoItemImage | null;
      previewVideoUrl: string | null;
      fullVideoUrl: string | null;
      alt: string | null;
      displayMode: "fullscreen" | "stacked" | null;
    }> | null;
  } | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;
// Variable: allProjectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current,    category  }
export type AllProjectSlugsQueryResult = Array<{
  slug: string | null;
  category: "foto" | "movement-direction" | "performance" | null;
}>;
// Variable: projectsByCategoryQuery
// Query: *[_type == "project" && category == $category] | order(title asc) {    _id,    title,    "slug": slug.current,    featuredImage,    description  }
export type ProjectsByCategoryQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: BlockContent | null;
}>;
// Variable: sitemapQuery
// Query: *[_type == "project" && defined(slug.current)] | order(_updatedAt desc) {    "slug": slug.current,    category,    _updatedAt  }
export type SitemapQueryResult = Array<{
  slug: string | null;
  category: "foto" | "movement-direction" | "performance" | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"settings\" && _id == \"siteSettings\"][0]{\n    title,\n    description,\n    footerLeftText,\n    footerRightText,\n    footerCenterText,\n    ogImage\n  }\n": SettingsQueryResult;
    "\n  *[_type == \"homepage\" && _id == \"homepage\"][0]{\n    _id,\n    title,\n    fotoImage,\n    movementDirectionImage,\n    performanceImage,\n    \"previewVideoUrl\": previewVideo.asset->url,\n    seoTitle,\n    seoDescription\n  }\n": HomepageQueryResult;
    "\n  *[_type == \"about\" && _id == \"about\"][0]{\n    _id,\n    mainText,\n    selectedClients,\n    selectedClientsDescription,\n    specialties,\n    contact[]{\n      _key,\n      label,\n      linkType,\n      url,\n      email\n    },\n    backgroundColor,\n    seoTitle,\n    seoDescription\n  }\n": AboutQueryResult;
    "\n  {\n    \"foto\": *[_type == \"project\" && category == \"foto\"] | order(title asc) {\n      _id,\n      title,\n      \"slug\": slug.current\n    },\n    \"movementDirection\": *[_type == \"project\" && category == \"movement-direction\"] | order(title asc) {\n      _id,\n      title,\n      \"slug\": slug.current\n    },\n    \"performance\": *[_type == \"project\" && category == \"performance\"] | order(title asc) {\n      _id,\n      title,\n      \"slug\": slug.current\n    }\n  }\n": AllProjectsForNavQueryResult;
    "\n  *[_type == \"project\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    category,\n    description,\n    relevantLinks[]{\n      _key,\n      label,\n      linkType,\n      url,\n      email\n    },\n    featuredImage,\n    leftColumn{\n      photos[]{\n        _key,\n        \"isVideo\": coalesce(isVideo, false),\n        image,\n        previewVideoUrl,\n        fullVideoUrl,\n        alt,\n        displayMode\n      }\n    },\n    rightColumn{\n      photos[]{\n        _key,\n        \"isVideo\": coalesce(isVideo, false),\n        image,\n        previewVideoUrl,\n        fullVideoUrl,\n        alt,\n        displayMode\n      }\n    },\n    seoTitle,\n    seoDescription\n  }\n": ProjectBySlugQueryResult;
    "\n  *[_type == \"project\" && defined(slug.current)]{\n    \"slug\": slug.current,\n    category\n  }\n": AllProjectSlugsQueryResult;
    "\n  *[_type == \"project\" && category == $category] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    featuredImage,\n    description\n  }\n": ProjectsByCategoryQueryResult;
    "\n  *[_type == \"project\" && defined(slug.current)] | order(_updatedAt desc) {\n    \"slug\": slug.current,\n    category,\n    _updatedAt\n  }\n": SitemapQueryResult;
  }
}
